### ISSUE TITLE
add "Mag" in front of all peak magnitude metric names

### ISSUE THREAD

**Issue by alyssaobester** [ceff-tech/ffc_api_client#44]
I think we talked about this, but just to make sure we don't forget, could we change the metric names so that the peak metrics have the word "Mag" in them? So for example, instead of Peak_10, it'd be Peak_Mag_10.

**Comment by nickrsan** [comment]
Hey Alyssa,

I remember talking about this, but deciding against it because I thought the official names didn't include the Mag so we were keeping them matching the official names. Did those get changed to be more consistent, or were you thinking the package could be consistent even if it's different from the names used in CEFF?

**Comment by alyssaobester** [comment]
The official names haven't been changed (as far as I know), but I was hoping that within the package they could be consistent, and then we could ask Ted about changing the names officially.

**Comment by nickrsan** [comment]
OK, I think we could do this, but I'd want to do it with some kind of setting or flag where the default is to leave the names matching whatever the approved names are, and the flag would toggle them to be internally consistent. That way, if anyone else uses the package, they won't be surprised at names they see as broken, even if they're better :). What would you think of that?

**Comment by nickrsan** [comment]
To elaborate, I'm not even thinking of it being a parameter to any functions - i think I'd prefer it just be a setting people can change in the package globally - that way, if they change the names, we can rip that out without breaking anyone's code like we would if it was a parameter

**Comment by alyssaobester** [comment]
That sounds good. We can also leave it as is!

**Comment by nickrsan** [comment]
Hey Alyssa,

I just added some new functionality. It defaults to leaving things alone, but if you call `ffcAPIClient::force_consistent_names(TRUE)` before calling any of the functions that process data, it'll return names like `Peak_Mag_2` instead of `Peak_2`. If you turn it on and want to turn it back off, run `ffcAPIClient::force_consistent_names(FALSE)`. This function is in the documentation as well. Whenever you work with this next, if you could update and try it out, that'd be great!
